/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GamesRouteImport } from './routes/games'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as SportsSportRouteImport } from './routes/sports.$sport'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GamesRoute,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => PlayersRoute,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SportsRoute,
} as any)
const SportsSportRoute = SportsSportRouteImport.update({
  id: '/$sport',
  path: '/$sport',
  getParentRoute: () => SportsRoute,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/games': typeof GamesRouteWithChildren
  '/players': typeof PlayersRouteWithChildren
  '/sports': typeof SportsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/watch': typeof WatchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sports/$sport': typeof SportsSportRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/sports/': typeof SportsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/api/media/$': typeof ApiMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/games': typeof GamesRouteWithChildren
  '/players': typeof PlayersRouteWithChildren
  '/watch': typeof WatchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sports/$sport': typeof SportsSportRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/sports': typeof SportsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/api/media/$': typeof ApiMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/games': typeof GamesRouteWithChildren
  '/players': typeof PlayersRouteWithChildren
  '/sports': typeof SportsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/watch': typeof WatchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/sports/$sport': typeof SportsSportRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/sports/': typeof SportsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/api/media/$': typeof ApiMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/auth'
    | '/games'
    | '/players'
    | '/sports'
    | '/teams'
    | '/watch'
    | '/admin'
    | '/articles/$slug'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/sports/$sport'
    | '/teams/$teamId'
    | '/articles/'
    | '/sports/'
    | '/teams/'
    | '/api/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/games'
    | '/players'
    | '/watch'
    | '/admin'
    | '/articles/$slug'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/sports/$sport'
    | '/teams/$teamId'
    | '/articles'
    | '/sports'
    | '/teams'
    | '/api/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/articles'
    | '/auth'
    | '/games'
    | '/players'
    | '/sports'
    | '/teams'
    | '/watch'
    | '/_authenticated/admin'
    | '/articles/$slug'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/sports/$sport'
    | '/teams/$teamId'
    | '/articles/'
    | '/sports/'
    | '/teams/'
    | '/api/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  GamesRoute: typeof GamesRouteWithChildren
  PlayersRoute: typeof PlayersRouteWithChildren
  SportsRoute: typeof SportsRouteWithChildren
  TeamsRoute: typeof TeamsRouteWithChildren
  WatchRoute: typeof WatchRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/sports/': {
      id: '/sports/'
      path: '/'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof SportsRoute
    }
    '/sports/$sport': {
      id: '/sports/$sport'
      path: '/$sport'
      fullPath: '/sports/$sport'
      preLoaderRoute: typeof SportsSportRouteImport
      parentRoute: typeof SportsRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface GamesRouteChildren {
  GamesGameIdRoute: typeof GamesGameIdRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameIdRoute: GamesGameIdRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface PlayersRouteChildren {
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

interface SportsRouteChildren {
  SportsSportRoute: typeof SportsSportRoute
  SportsIndexRoute: typeof SportsIndexRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSportRoute: SportsSportRoute,
  SportsIndexRoute: SportsIndexRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  GamesRoute: GamesRouteWithChildren,
  PlayersRoute: PlayersRouteWithChildren,
  SportsRoute: SportsRouteWithChildren,
  TeamsRoute: TeamsRouteWithChildren,
  WatchRoute: WatchRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
